### ISSUE TITLE
Compability with Nextcloud?

### ISSUE THREAD

**Issue by FirstS0ul** [privacyidea/privacyidea-owncloud-app#103]
Is there a possible way, that this is compatible with the latest Nextcloud?
Thanks

**Comment by nilsbehlen** [comment]
Hi, no it is not compatible. We would need to make an extra app for nextcloud (which would look a awful lot like this).
We have currently decided against doing that because the demand is not really there.
You might be able to make things work by copying files etc but thats without warranty im afraid.
