### ISSUE TITLE
OwnCloud fails to check the PIN for PUSH-tokens

### ISSUE THREAD

**Issue by jp-hoehmann** [privacyidea/privacyidea-owncloud-app#72]
We currently deliver a PUSH-token to the user without checking first, whether the user possesses the PIN associated with the token.

**Comment by cornelinux** [comment]
This is done by design! The Push token only works in a challenge response mode with a triggerchallenge. When using triggerchallenge no token is ever queired with the PIN. This is actually what the triggerchallenge is for.
I am closing this issue, since it works as designed. But we can still discuss this for a better understanding.
