### ISSUE TITLE
Owncloud could check whether a challenge is expired

### ISSUE THREAD

**Issue by jp-hoehmann** [privacyidea/privacyidea-owncloud-app#73]
We do not yet check, if a challenge is still valid, when the user tries to sign in using a PUSH-token. Since expired challenges may linger for quite a while, before the janitor cleans them up, this is a concern.

**Comment by cornelinux** [comment]
This might be a concern but it is not a bug. If the client (owncloud app) answers a challenge, that is not valid anymore, privacyIDEA server will reject this answer.
Imho, it is not necessary for the client to check the validity of the challenge.

**Comment by fredreichbier** [comment]
If I understand correctly, after having triggered a push challenge, the app currently polls the ``/token/challenges`` endpoint in order to check if the challenge has been answered, and authenticates the user if it finds a matching challenge with ``otp_received`` and ``otp_valid`` set to true, regardless of the expiration datetime.

In the privacyIDEA server, the challenge janitor does remove expired challenges, but does so only occasionally (e.g. when another challenge is created). As a consequence, expired challenges may stay in the challenge table for a while. Hence, I think it would be safer if the app always checks the expiration datetime, in order to prevent users from being authenticated with expired challenges that happen to stay in the challenge table.

**Comment by cornelinux** [comment]
The challenge can only be answered and marked as answered, if the correct repsonse is received by privacyIDEA in the expiration time. So it does not really matter, if the app will look *after* the expiration time. 
The expiration time was always used for the time, in which the challenge has to be answered. Till now it was not the time, that defines, in which the client has to retrieve this information. 
If this really makes sense we can do this as an enhancements but I really really do not want to overcomplicate the client logic.

But to make one thing clear: It was *never* the intention for a client app like owncloud to check if a challenge is valid. This is the realm of the privacyidea server. So I would totally downvote this issue! Keep the client plugins simple and maintable.

**Comment by cornelinux** [comment]
(see https://github.com/privacyidea/privacyidea/issues/1837#issuecomment-528720027 and  https://github.com/privacyidea/privacyidea/issues/1838)

**Comment by jp-hoehmann** [comment]
Closing this for now, as it works as intended.
