### ISSUE TITLE
Problem with owncloud 10.11

### ISSUE THREAD

**Issue by georgezip** [privacyidea/privacyidea-owncloud-app#93]
privacyIDEA Two Factor Authentication doesn't work on owncloud 10.11
When I click test button  on PrivacyIdea config site (Owncloud / settings /addons) there is an error:

Passing in the "body" request option as an array to send a request is not supported. Please use the "form_params" request option to send a application/x-www-form-urlencoded request, or the "multipart" request option to send a multipart/form-data request.

Also 2fa doesnt work on login site with error:

Failed to fetch authentication token.

before update on owncloud 10.10 everything was ok 
tested on:
privacyIDEA Two Factor Authentication version 3.0
privacyIDEA server 3.8
owncloud 10.11

**Comment by lukasmatusiewicz** [comment]
Thank you! We will check this issue.

**Comment by lukasmatusiewicz** [comment]
OC 10.11 has updated the guzzle (HTTP-Client) which has abandoned the "body" requests, which up to now been accepted. There is no info about this deprecation on the OC side. I think that this dependency update should be planned in v11.0 since it causes a compatibility issue.

We adjust our plugin to work around this problem. A proper fix should be done soon, but we need some time to test this modification.

**Comment by lukasmatusiewicz** [comment]
This solution isn't working on 10.8:
`No method can handle the form_params config key`
Waiting for a proper solution or walkaround from the core side: https://github.com/owncloud/core/issues/40649.

**Comment by nilsbehlen** [comment]
Is it possible to get the owncloud version in the code and use the httpclient depending on that version?

**Comment by lukasmatusiewicz** [comment]
OC suggests this way too... I'll make some research.

**Comment by lukasmatusiewicz** [comment]
Ok. I found a good solution to adjust the request option up to the ownCloud version.
The backward compatibility test - passed.
